configured_endpoints: 50
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/derenrich%2Fpy-wikibase-rest-stainless-a9f0915ffba299c61621d1260069303d701d41d1cd701e4e0634d41febf43633.yml
